# Generated by Django 4.1.3 on 2023-06-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutQuery',
            new_name='ContactQuery',
        ),
    ]
