# Generated by Django 4.1.3 on 2023-07-01 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='postedDate',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
    ]
