# Generated by Django 4.1.3 on 2023-07-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0006_signup_alter_blog_posteddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='UserName',
            new_name='userName',
        ),
    ]
