# Generated by Django 4.1.3 on 2023-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0007_rename_email_signup_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='userName',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
