# Generated by Django 4.1.3 on 2023-07-02 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0008_remove_signup_username_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postedDate',
            field=models.DateField(default=datetime.date(2023, 7, 2)),
        ),
    ]
