# Generated by Django 4.1.3 on 2023-07-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0009_alter_blog_posteddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
